INSERT ALL
  INTO station (id, city, statecode) VALUES (794, 'Kissee Mills', 'MO')
  INTO station (id, city, statecode) VALUES (824, 'Loma Mar', 'CA')
  INTO station (id, city, statecode) VALUES (603, 'Sandy Hook', 'CT')
  INTO station (id, city, statecode) VALUES (478, 'Tipton', 'IN')
  INTO station (id, city, statecode) VALUES (619, 'Arlington', 'CO')
  INTO station (id, city, statecode) VALUES (711, 'Turner', 'AR')
  INTO station (id, city, statecode) VALUES (839, 'Slidell', 'LA')
  INTO station (id, city, statecode) VALUES (411, 'Negreet', 'LA')
  INTO station (id, city, statecode) VALUES (588, 'Glencoe', 'KY')
  INTO station (id, city, statecode) VALUES (665, 'Chelsea', 'IA')
  INTO station (id, city, statecode) VALUES (342, 'Chignik Lagoon', 'AK')
  INTO station (id, city, statecode) VALUES (733, 'Pelahatchie', 'MS')
  INTO station (id, city, statecode) VALUES (441, 'Hanna City', 'IL')
  INTO station (id, city, statecode) VALUES (811, 'Dorrance', 'KS')
  INTO station (id, city, statecode) VALUES (698, 'Albany', 'CA')
  INTO station (id, city, statecode) VALUES (325, 'Monument', 'KS')
  INTO station (id, city, statecode) VALUES (414, 'Manchester', 'MD')
  INTO station (id, city, statecode) VALUES (113, 'Prescott', 'IA')
  INTO station (id, city, statecode) VALUES (971, 'Graettinger', 'IA')
  INTO station (id, city, statecode) VALUES (266, 'Cahone', 'CO')
  INTO station (id, city, statecode) VALUES (617, 'Sturgis', 'MS')
  INTO station (id, city, statecode) VALUES (661, 'Payson', 'AZ')
  INTO station (id, city, statecode) VALUES (365, 'Payson', 'IL')
  INTO station (id, city, statecode) VALUES (755, 'Sturgis', 'MI')
  INTO station (id, city, statecode) VALUES (459, 'Harmony', 'IN')
  INTO station (id, city, statecode) VALUES (522, 'Harmony', 'MN')
  INTO station (id, city, statecode) VALUES (495, 'Upperco', 'MD')
  INTO station (id, city, statecode) VALUES (473, 'Highwood', 'IL')
  INTO station (id, city, statecode) VALUES (959, 'Waipahu', 'HI')
  INTO station (id, city, statecode) VALUES (571, 'Tyler', 'MN')
  INTO station (id, city, statecode) VALUES (399, 'Republic', 'MI')
  INTO station (id, city, statecode) VALUES (426, 'Millville', 'CA')
  INTO station (id, city, statecode) VALUES (844, 'Aguanga', 'CA')
  INTO station (id, city, statecode) VALUES (321, 'Bowdon Junction', 'GA')
  INTO station (id, city, statecode) VALUES (606, 'Morenci', 'AZ')
  INTO station (id, city, statecode) VALUES (957, 'South El Monte', 'CA')
  INTO station (id, city, statecode) VALUES (833, 'Hoskinston', 'KY')
  INTO station (id, city, statecode) VALUES (843, 'Talbert', 'KY')
  INTO station (id, city, statecode) VALUES (166, 'Mccomb', 'MS')
  INTO station (id, city, statecode) VALUES (339, 'Kirk', 'CO')
  INTO station (id, city, statecode) VALUES (328, 'Monroe', 'LA')
  INTO station (id, city, statecode) VALUES (779, 'Del Mar', 'CA')
  INTO station (id, city, statecode) VALUES (646, 'Greens Fork', 'IN')
  INTO station (id, city, statecode) VALUES (756, 'Garden City', 'AL')
  INTO station (id, city, statecode) VALUES (384, 'Amo', 'IN')
  INTO station (id, city, statecode) VALUES (518, 'Vulcan', 'MO')
  INTO station (id, city, statecode) VALUES (188, 'Prairie Du Rocher', 'IL')
  INTO station (id, city, statecode) VALUES (161, 'Alanson', 'MI')
  INTO station (id, city, statecode) VALUES (531, 'North Middletown', 'KY')
SELECT * FROM dual