INSERT ALL
  INTO city (id, name, countrycode, district, population) VALUES (6, 'Rotterdam', 'NLD', 'Zuid-Holland', 593321)
  INTO city (id, name, countrycode, district, population) VALUES (19, 'Zaanstad', 'NLD', 'Noord-Holland', 135621)
  INTO city (id, name, countrycode, district, population) VALUES (214, 'Porto Alegre', 'BRA', 'Rio Grande do Sul', 1314032)
  INTO city (id, name, countrycode, district, population) VALUES (397, 'Lauro de Freitas', 'BRA', 'Bahia', 109236)
  INTO city (id, name, countrycode, district, population) VALUES (547, 'Dobric', 'BGR', 'Varna', 100399)
  INTO city (id, name, countrycode, district, population) VALUES (552, 'Bujumbura', 'BDI', 'Bujumbura', 300000)
  INTO city (id, name, countrycode, district, population) VALUES (554, 'Santiago de Chile', 'CHL', 'Santiago', 4703954)
  INTO city (id, name, countrycode, district, population) VALUES (3073, 'Essen', 'DEU', 'Nordrhein-Westfalen', 599515)
  INTO city (id, name, countrycode, district, population) VALUES (3169, 'Apia', 'WSM', 'Upolu', 35900)
  INTO city (id, name, countrycode, district, population) VALUES (762, 'Rotterdam', 'NLD', 'Zuid-Holland', 593321)
  INTO city (id, name, countrycode, district, population) VALUES (4061, 'Fall River', 'USA', 'Massachusetts', 90555)
  INTO city (id, name, countrycode, district, population) VALUES (4058, 'Boulder', 'USA', 'Colorado', 91238)
  INTO city (id, name, countrycode, district, population) VALUES (3815, 'El Paso', 'USA', 'Texas', 563662)
  INTO city (id, name, countrycode, district, population) VALUES (3878, 'Scottsdale', 'USA', 'Arizona', 202705)
  INTO city (id, name, countrycode, district, population) VALUES (3973, 'Concord', 'USA', 'California', 121780)
  INTO city (id, name, countrycode, district, population) VALUES (3965, 'Corona', 'USA', 'California', 124966)
  INTO city (id, name, countrycode, district, population) VALUES (1520, 'Cesena', 'ITA', 'Emilia-Romagna', 89852)
  INTO city (id, name, countrycode, district, population) VALUES (1613, 'Neyagawa', 'JPN', 'Osaka', 257315)
  INTO city (id, name, countrycode, district, population) VALUES (1630, 'Ageo', 'JPN', 'Saitama', 209442)
  INTO city (id, name, countrycode, district, population) VALUES (1661, 'Sayama', 'JPN', 'Saitama', 162472)
  INTO city (id, name, countrycode, district, population) VALUES (1681, 'Omuta', 'JPN', 'Fukuoka', 142889)
  INTO city (id, name, countrycode, district, population) VALUES (1739, 'Tokuyama', 'JPN', 'Yamaguchi', 107078)
  INTO city (id, name, countrycode, district, population) VALUES (1793, 'Novi Sad', 'SRB', 'Vojvodina', 179626)
SELECT * FROM dual